### PR TITLE
Change Add to project bot to one what uses new Projects API

### PR DESCRIPTION
**Pull request by uhbif19**

### CODE REVIEW

**Comment by uhbif19** [comment]
`Act` check fails with error. Not sure if it is error in action or `act`.

**Comment by nazrhom** [comment]
Hey @uhbif19 I noticed these changes are targeting master, is that intended?

**Comment by uhbif19** [comment]
@nazrhom I think this workflows only work in master, no? Also previous version is already in master. And this is our change not affecting uses, so I see no reason not to put it in master.

**Review by MangoIV — APPROVED** [review]

**Comment by uhbif19** [comment]
@MangoIV This cannot break CI check, AFAIK, as Github treating these workflows as separate things.

**Pull request merged**
